### ISSUE TITLE
Error connecting to Readarr

### ISSUE THREAD

**Issue by spencerskinner99** [TheWicklowWolf/BookBounty#19]
Hi 

I am having issues getting bookbounty to pull wanted books from readarr 

my compose is: 
```
bookbounty:
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    environment:
      - PUID=1001
      - PGID=1001
      - readarr_address=http://192.168.2.32:8787/readarr/
      - readarr_api_key=xxx
    volumes:
      - /Docker_Configs/media-control/bookbounty:/bookbounty/config
      - /mnt/VMRoot/VMMedia/complete/books:/downloads/complete/books
    restart: unless-stopped
    depends_on:
     - "vpn"
    network_mode: "service:vpn"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"
```

and the error I am getting is 
```

[2024-09-24 15:30:43 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2024-09-24 15:30:43 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-09-24 15:30:43 +0000] [1] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-09-24 15:30:43 +0000] [7] [INFO] Booting worker with pid: 7
**************************************************
BookBounty Version: 0.1.7
**************************************************
10.0.8.2 - - [2024-09-24 15:30:43] "GET /socket.io/?EIO=4&transport=polling&t=P8af_tK HTTP/1.1" 200 254 0.000539
10.0.8.2 - - [2024-09-24 15:30:43] "POST /socket.io/?EIO=4&transport=polling&t=P8af_ti&sid=kf47zGr8RQdk22_DAAAA HTTP/1.1" 200 198 0.002310
10.0.8.2 - - [2024-09-24 15:30:44] "GET /socket.io/?EIO=4&transport=polling&t=P8af_tj&sid=kf47zGr8RQdk22_DAAAA HTTP/1.1" 200 157 0.000108
10.0.8.2 - - [2024-09-24 15:30:44] "GET /socket.io/?EIO=4&transport=polling&t=P8af_u6&sid=kf47zGr8RQdk22_DAAAA HTTP/1.1" 200 157 0.000112
10.0.8.2 - - [2024-09-24 15:30:45] "GET / HTTP/1.1" 200 9614 0.006537
10.0.8.2 - - [2024-09-24 15:30:45] "GET /static/style.css HTTP/1.1" 304 177 0.001225
10.0.8.2 - - [2024-09-24 15:30:45] "GET /static/readarr.svg HTTP/1.1" 304 180 0.000728
10.0.8.2 - - [2024-09-24 15:30:45] "GET /static/libgen.png HTTP/1.1" 304 179 0.000424
10.0.8.2 - - [2024-09-24 15:30:45] "GET /static/script.js HTTP/1.1" 304 178 0.000837
10.0.8.2 - - [2024-09-24 15:30:45] "GET /socket.io/?EIO=4&transport=polling&t=P8ag0Fd HTTP/1.1" 200 254 0.000317
10.0.8.2 - - [2024-09-24 15:30:45] "POST /socket.io/?EIO=4&transport=polling&t=P8ag0GR&sid=QgwJPyKWQVTOOk8uAAAC HTTP/1.1" 200 198 0.000791
10.0.8.2 - - [2024-09-24 15:30:45] "GET /socket.io/?EIO=4&transport=polling&t=P8ag0GR.0&sid=QgwJPyKWQVTOOk8uAAAC HTTP/1.1" 200 310 0.000135
10.0.8.2 - - [2024-09-24 15:30:45] "GET /socket.io/?EIO=4&transport=polling&t=P8ag0Gf&sid=QgwJPyKWQVTOOk8uAAAC HTTP/1.1" 200 157 0.000150
10.0.8.2 - - [2024-09-24 15:30:45] "GET /static/logo.png HTTP/1.1" 304 178 0.000796
Accessing Readarr API
Error Getting Missing Books: Expecting value: line 1 column 1 (char 0)
Accessing Readarr API
Error Getting Missing Books: Expecting value: line 1 column 1 (char 0)

```

I am unsure what is causing the issue, I have verified the API key to be correct but am a bit stuck. 

Thanks in advance for any help.
