### ISSUE TITLE
error connectiong to readarr

### ISSUE THREAD

**Issue by pdelass** [TheWicklowWolf/BookBounty#25]
Hi @TheWicklowWolf,

Well, it deploys well, even if the "permission denied" error is still present, but I can't connect it with readarr...
I don't know if it's related to the permission and the user in 1000:1000... or something else?

I understand that my PUID/PGID/TZ variables are probably useless, but in case of doubt...

Here are my new data :

```
services:
  bookbounty:
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    environment:
      - readarr_address=http://192.168.1.23:8787
      - readarr_api_key=XXXXXXXXXXXXXXXXXXXXXX
      - sync_schedule=2, 20
      - selected_path_type=folder
      - library_scan_on_completion=True
      - selected_language=French
      - preferred_extensions_fiction=.epub
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    ports:
      - 5028:5000
    volumes:
      - /volume1/docker/bookbounty:/bookbounty/config
      - /volume1/docker/calibre/downloads:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
``` 

and 

```
[2024-11-01 16:38:00 +0100] [1] [INFO] Starting gunicorn 23.0.0
[2024-11-01 16:38:00 +0100] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-11-01 16:38:00 +0100] [1] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-01 16:38:00 +0100] [7] [INFO] Booting worker with pid: 7
**************************************************
BookBounty Version: 0.1.7
**************************************************
Error Saving Config: [Errno 13] Permission denied: 'config/settings_config.json'
172.20.0.1 - - [2024-11-01 16:38:09] "GET /socket.io/?EIO=4&transport=polling&t=PBeO6X3 HTTP/1.1" 200 254 0.025172
172.20.0.1 - - [2024-11-01 16:38:09] "POST /socket.io/?EIO=4&transport=polling&t=PBeO7H2&sid=ePtdWmLRM-C0hqckAAAA HTTP/1.1" 200 198 0.019247
172.20.0.1 - - [2024-11-01 16:38:09] "GET /socket.io/?EIO=4&transport=polling&t=PBeO7H4&sid=ePtdWmLRM-C0hqckAAAA HTTP/1.1" 200 157 0.000399
172.20.0.1 - - [2024-11-01 16:38:09] "GET /socket.io/?EIO=4&transport=polling&t=PBeO7Hy&sid=ePtdWmLRM-C0hqckAAAA HTTP/1.1" 200 157 0.000373
172.20.0.1 - - [2024-11-01 16:38:35] "GET / HTTP/1.1" 200 9614 0.504104
172.20.0.1 - - [2024-11-01 16:38:35] "GET /socket.io/?EIO=4&transport=polling&t=PBeODfs HTTP/1.1" 200 254 0.026982
172.20.0.1 - - [2024-11-01 16:38:35] "POST /socket.io/?EIO=4&transport=polling&t=PBeODlh&sid=yYO6HIA1UDe1-vpbAAAC HTTP/1.1" 200 198 0.004019
172.20.0.1 - - [2024-11-01 16:38:36] "GET /static/style.css HTTP/1.1" 200 618 0.207423
172.20.0.1 - - [2024-11-01 16:38:36] "GET /static/script.js HTTP/1.1" 200 10172 0.839786
172.20.0.1 - - [2024-11-01 16:38:36] "GET /static/readarr.svg HTTP/1.1" 200 3626 0.049125
172.20.0.1 - - [2024-11-01 16:38:37] "GET /static/libgen.png HTTP/1.1" 200 9554 0.123804
172.20.0.1 - - [2024-11-01 16:38:37] "GET /socket.io/?EIO=4&transport=polling&t=PBeOE1w HTTP/1.1" 200 254 0.000651
172.20.0.1 - - [2024-11-01 16:38:37] "GET /static/logo.png HTTP/1.1" 200 18006 0.011172
172.20.0.1 - - [2024-11-01 16:38:37] "POST /socket.io/?EIO=4&transport=polling&t=PBeOE5q&sid=2tL9xP2rmpQGm5_FAAAE HTTP/1.1" 200 198 0.002876
172.20.0.1 - - [2024-11-01 16:38:37] "GET /socket.io/?EIO=4&transport=polling&t=PBeOE5r&sid=2tL9xP2rmpQGm5_FAAAE HTTP/1.1" 200 310 0.000975
172.20.0.1 - - [2024-11-01 16:38:37] "GET /socket.io/?EIO=4&transport=polling&t=PBeOE70&sid=2tL9xP2rmpQGm5_FAAAE HTTP/1.1" 200 157 0.000397
172.20.0.1 - - [2024-11-01 16:38:37] "POST /socket.io/?EIO=4&transport=polling&t=PBeOE72&sid=2tL9xP2rmpQGm5_FAAAE HTTP/1.1" 200 198 0.000860
172.20.0.1 - - [2024-11-01 16:38:37] "GET /socket.io/?EIO=4&transport=polling&t=PBeOE7J&sid=2tL9xP2rmpQGm5_FAAAE HTTP/1.1" 200 157 0.000979
Accessing Readarr API
Error Getting Missing Books: HTTPConnectionPool(host='192.168.1.23', port=8787): Max retries exceeded with url: /api/v1/wanted/missing?apikey=XXXXXXXXXXXXXXXXXXXXXX&page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcea8880800>, 'Connection to 192.168.1.23 timed out. (connect timeout=120.0)'))
``` 

Note that when i tried manually :
http://192.168.1.23:8787/api/v1/wanted/missing?apikey=XXXXXXXXXXXXXXXXXXXXXX&page=1
I have the results i would like to...

Thanks a lot for your return !
