### ISSUE TITLE
Error Downloading library.gift

### ISSUE THREAD

**Issue by sumisukyo** [TheWicklowWolf/BookBounty#33]
`Error Downloading: HTTPConnectionPool(host='library.gift', port=80): Max retries exceeded with url: /fiction/66414CFEE16ADC64C19A54853AEDEF44 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7b42e14ada60>: Failed to resolve 'library.gift' ([Errno -5] Name has no usable address)"))`

Sorry No idea whats going on here ?
Was the link for libgen.is switched to library.gift ?

**Comment by sumisukyo** [comment]
```
  bookbounty:
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    environment:
      - PUID=0
      - PGID=0
      - readarr_address=http://localhost:8787
      - selected_path_type=file
      - libgen_address=http://libgen.is
      - library_scan_on_completion=True
      - WEBUI_PORT=5000
    volumes:
      - /home/sumisukyo/docker:/bookbounty/config
      - /home/sumisukyo/docker:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    restart: unless-stopped
```

Here is the stack
It's behind a gluetun
