### ISSUE TITLE
All search results show "No Link Found"

### ISSUE THREAD

**Issue by firmlyundecided** [TheWicklowWolf/BookBounty#40]
Running the latest version of BookBounty on a Synology DS1522+ via Container Manager (docker compose). BookBounty successfully reads missing list from Readarr, but any search results in "No Link Found", even when item can be found manually on libgen.is.

Attempted mitigation by adding `selected_language=all` per #17, as well as miscellaneous other changes to environment variables. Issue persists. 

Logs:

```
Readarr library scan started | stderr
-- | --
04/23/2025 23:48 | Downloading Finished | stderr
04/23/2025 23:48 | Searching for Book: Alan Lightman - Einstein's Dreams - Allowed Languages: english | stderr
04/23/2025 23:48 | Accessing Readarr API | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /static/logo.png HTTP/1.1" 200 18006 0.018064 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /socket.io/?EIO=4&transport=polling&t=PPbwOGK&sid=Mg_MUQsElNFy7xoxAAAA HTTP/1.1" 200 157 0.000226 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /socket.io/?EIO=4&transport=polling&t=PPbwOFn&sid=Mg_MUQsElNFy7xoxAAAA HTTP/1.1" 200 157 0.000264 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /socket.io/?EIO=4&transport=polling&t=PPbwOF0&sid=Mg_MUQsElNFy7xoxAAAA HTTP/1.1" 200 310 0.000238 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "POST /socket.io/?EIO=4&transport=polling&t=PPbwOE_&sid=Mg_MUQsElNFy7xoxAAAA HTTP/1.1" 200 199 0.001749 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /socket.io/?EIO=4&transport=polling&t=PPbwOEi HTTP/1.1" 200 276 0.000581 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /static/script.js HTTP/1.1" 200 10172 0.001394 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /static/libgen.png HTTP/1.1" 200 9554 0.001423 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /static/readarr.svg HTTP/1.1" 200 3626 0.001521 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET /static/style.css HTTP/1.1" 200 618 0.001814 | stderr
04/23/2025 23:48 | 192.168.4.247 - - [2025-04-23 23:48:44] "GET / HTTP/1.1" 200 9614 0.012183 | stderr
04/23/2025 23:48 | Loading Settings via config file | stderr
04/23/2025 23:48 | ************************************************** | stderr
04/23/2025 23:48 |   | stderr
04/23/2025 23:48 | BookBounty Version: 0.2.5

```

Compose file:

```
services:
  bookbounty:
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    ports:
      - 6000:5000
    environment:
      - PUID=1030
      - PGID=100
#      - TZ=America/New_York
      - readarr_address=http://192.168.4.241:8787
      - readarr_api_key=correct_api_key
      - selected_language=all
#      - libgen_address=http://libgen.is # The URL for Library Genesis. The only supported URL at present is http://libgen.is.
#      - sync_schedule=14 # Scheduled hours to run e.g. 14 for 2pm (comma separated values in 24hr)
#      - minimum_match_ratio=80 # Minimum percentage for a match. Defaults to 90.
      - selected_path_type=file # Select Download Structure (file or folder). Defaults to file.
#      - search_type=fiction # Select Search Type (fiction or non-fiction). Defaults to fiction.
#      - library_scan_on_completion=true # Whether to scan Readarr Library on completion. Defaults to True.
#      - thread_limit=1 # Max number of threads to use. Defaults to 1.
#      - preferred_extensions_fiction=".epub, .mobi, .azw3" # Filter fiction download by extension (comma separated). Defaults to .epub, .mobi, .azw3, .djvu.
#      - preferred_extensions_non_fiction=".epub, .mobi, .azw3" # Filter fiction download by extension (comma separated). Defaults to .epub, .mobi, .azw3, .djvu.
#      - search_shortened_title=true # Use shortened title when searching (remove everything after :). Defaults to False.
    volumes:
      - /volume1/docker/appdata/bookbounty/:/bookbounty/config
      - /volume1/data/bookbounty_downloads:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

Any insights or help troubleshooting would be appreciated. Thanks!
