### ISSUE TITLE
I am having an issue with selected_path_type

### ISSUE THREAD

**Issue by yoannfelix** [TheWicklowWolf/BookBounty#6]
I am using BookBounty on Unraid and I have set selected_path_type=folder but it keeps reverting back to file. 

I have changed the configuration in settings_config.json as well as the docker template variable but the parameter keeps changing back to file.

I have tried setting the settings_config.json to read only but it did not help.

**Comment by TheWicklowWolf** [comment]
Strange, are you using the latest image? You can use `docker compose pull && docker compose up -d` to get the latest version.

What is in your docker-compose? 
Also make sure that you change your ` - /path/to/downloads:/bookbounty/downloads` to the root folder when using `selected_path_type=folder`

```
services:
  bookbounty:
    image: thewicklowwolf/bookbounty:latest
    container_name: bookbounty
    ports:
      - 5000:5000
    volumes:
      - /path/to/config:/bookbounty/config
      - /path/to/downloads:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - selected_path_type=folder
    restart: unless-stopped
```
